language: php

php:
  - 7.0
  - 7.1
  - 7.2

services:
  - mysql
  - redis

before_install:
  - export PHP_MAJOR="$(`phpenv which php` -r 'echo phpversion();' | cut -d '.' -f 1)"
  - export PHP_MINOR="$(`phpenv which php` -r 'echo phpversion();' | cut -d '.' -f 2)"
  - echo $PHP_MAJOR
  - echo $PHP_MINOR

install:
  - cd $TRAVIS_BUILD_DIR
  - bash test/_ci/install_swoole.sh
  - phpenv config-rm xdebug.ini
  - phpenv config-add test/_ci/ci.ini
  - bash test/_ci/setup_dbs.sh

before_script:
  - cd $TRAVIS_BUILD_DIR
  - composer config -g process-timeout 900 && composer update
  - cp test/.env.example test/.env

script: composer test
